/**:
  ros__parameters:
    # GUI configuration
    window_title: "Robot Control Hub - ROS2 VILA Integration"
    window_size: [1200, 800]
    
    # Update rates
    gui_update_rate: 20.0  # Hz (50ms)
    status_refresh_rate: 1.0  # Hz
    
    # Camera display
    camera_display_size: [320, 240]
    camera_update_rate: 5.0  # Hz
    
    # Movement controls
    default_movement_speed: 0.3
    default_movement_duration: 1.0
    default_turn_speed: 0.5
    
    # Safety
    movement_confirmation_required: false
    emergency_stop_confirmation: true
    
    # VILA interface
    vila_prompt_default: "Analyze the current camera view for navigation."
    vila_results_max_lines: 1000
