/**:
  ros__parameters:
    # Hardware configuration
    camera_device: 0
    camera_width: 640
    camera_height: 480
    camera_fps: 30
    
    # Sensor configuration
    sensor_simulation: true
    sensor_publish_rate: 10.0  # Hz
    status_publish_rate: 1.0   # Hz
    
    # Simulated sensor ranges
    battery_voltage_range: [10.0, 12.6]
    temperature_range: [20.0, 30.0]
    distance_range: [0.1, 3.0]
    cpu_usage_range: [10.0, 90.0]
    memory_usage_range: [30.0, 95.0]
    
    # Command execution
    command_ack_enabled: true
    command_timeout: 5.0
    
    # Image compression
    image_compression_quality: 80
    publish_compressed: true
